# Generated by Django 3.2.9 on 2021-11-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sitios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80)),
                ('longitud', models.FloatField()),
                ('latitud', models.FloatField()),
                ('fotografia', models.BinaryField(editable=True)),
            ],
        ),
    ]
